FROM python:3.12-slim

WORKDIR /app

# Since your docker-compose build context is ".", 
# this copies the entire project into /app
COPY service/requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY service/ ./service/
COPY database/ ./database/

EXPOSE 8000

# Update this line to the correct path
CMD ["python","-u", "service/ws/main.py"]
